### ISSUE TITLE
HTML: Index terms not hyperlinked and uses page numbers

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#106]
From @anermina:

> HTML uses page numbers and does not include hyperlinks. 

The Index section should provide hyperlinks to term usages.

_Originally posted by @anermina in https://github.com/metanorma/mn-samples-plateau/issues/156#issuecomment-2322895306_

**Comment by anermina** [comment]
Our HTML is fine. I was referring to the original HTML file in the comment. Apologies for the confusion. Closing this ticket.
