### ISSUE TITLE
Remove "Yu Gothic" from font list since it is not used

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#117]
https://github.com/metanorma/metanorma-plateau/blob/d23f2e1d79b0230c94b0f06981148a09dc6f6c78/lib/metanorma/plateau/processor.rb#L21

Not used in PDF XSLT at all:
* https://github.com/metanorma/mn-native-pdf/blob/24cf232e3da00f2c5a8cce9c82d62b8243c0c760/xslt_src/plateau.international-standard.core.xsl

**Comment by Intelligent2013** [comment]
> Not used in PDF XSLT at all:

@ronaldtse "Yu Gothic" is the main font in the Plateau documents:

https://github.com/metanorma/mn-native-pdf/blob/24cf232e3da00f2c5a8cce9c82d62b8243c0c760/xslt_src/common.xsl#L640

https://github.com/metanorma/metanorma-plateau/blob/d23f2e1d79b0230c94b0f06981148a09dc6f6c78/lib/isodoc/plateau/plateau.international-standard.xsl#L2198

The original requirement from https://github.com/metanorma/metanorma-plateau/issues/2#issuecomment-2123614316
> Japanese (primary): Yu Gothic (medium, bold)

**Comment by opoudjis** [comment]
So this issue is invalid? If so, please close it.

**Comment by ronaldtse** [comment]
Indeed, as @Intelligent2013 mentioned, "Yu Gothic" is the body text requirement. Thanks.
