### ISSUE TITLE
Change date format representation in the colophon to "令和6年 3月22日 発行" (now "令和六年9月30日 発行")

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-plateau#138]
as first reported on the [private repo](https://github.com/ReesePlews/ribose_discussions/issues/29), 

in the two plateau documents (sources/001-v4, sources/002-v4) on the last page of each document is the following text:

![image](https://github.com/user-attachments/assets/519d0da9-693a-45e2-8575-dea991b654e6)

the client would like to change how the date is rendered because the present method ( 令和六年9月30日 発行 ) mixes kanji (year as a kanji) and numbers (months and days).

i mentioned that there could be implications changing the date rendering if it that was formatted for the entire document.

i cannot seem to find where/how this text is added.   if the rendering of the date on the last page is indeed tied into a global date rendering style for the entire flavor, please let me know. more consideration would be needed then.

i am wondering if the date is taken from the "document.adoc" file, possibly 

```
:revdate: 2024-09-30
:published-date: 2024-09-30
```
but then somewhere in the template the year 2024 is being changed to japanese calendar "令和六年" as all kanji.
if you can tell me where that is i can try to edit it.

in the original published document (prior to metanorma conversion) the date on the last page was rendered as:
令和6年 3月22日 発行

the preference here is the rendering style using numbers as numbers not numbers as knaji. but i dont know the implications of saying that with respect to the overall plateau template. if it is possible to keep numbers as numbers in the date string even for the year, i think that would be more clear.

**Comment by ronaldtse** [comment]
The gist of this issue, is the date is now "令和六年9月30日 発行" and the client wants to change to "令和6年 3月22日 発行".

**Comment by ReesePlews** [comment]
yes @ronaldtse that is correct but it is being changed automatically for some reason and i want to be careful that changing this does not change something elsewhere in the document.

**Comment by ReesePlews** [comment]
perhaps the date format "令和六年x月x日 発行" is coming from the [JIS style](https://github.com/metanorma/metanorma-jis/issues/12).

**Comment by opoudjis** [comment]
It comes from here:

````
      def japanese_year(time)
        era_yr = time.era_year.to_i.localize(:ja)
          .to_rbnf_s("SpelloutRules", "spellout-numbering-year")
        "#{time.strftime('%JN')}#{era_yr}年"
      rescue StandardError
        time.year.to_s
      end
````

If you do not tell me how to format dates, I will go by what I find on Google Translate. In fact, in that issue, I quite explicitly said:

https://github.com/metanorma/metanorma-jis/issues/12


> I've used twitter_cldr to make the era year spelled out, the gem I've used is numeric.

So JIS should have paid attention a year ago. 

Japanese dates are used in bibliographic metadata about the current document (date published, date revised, date updated). That includes the colophon date, which is presumably the published date.

>  i want to be careful that changing this does not change something elsewhere in the document.

Any expectation that dates will be formatted one way in one spot and a different way in another spot is inconsistency that I will push back on.

**Comment by opoudjis** [comment]
And yes, this is also going to change Plateau, since Plateau inherits from JIS.

**Comment by opoudjis** [comment]
So the copyright statement changes from:

````
<p id="_">主 務 大 臣:経済産業大臣 制定:昭和 26.10.31 改正:平成十二年1月1日</p>
````

to

````
<p id="_">主 務 大 臣:経済産業大臣 制定:昭和 26.10.31 改正:平成12年1月1日</p>
````

and from

````
<p id="_">主 務 大 臣:経済産業大臣 制定:昭和 26.10.31 改正:平成十二年1月1日</p>
<p id="_">官 報 掲 載 日:平成十二年2月1日</p>
````

to

````
<p id="_">主 務 大 臣:経済産業大臣 制定:昭和 26.10.31 改正:平成12年1月1日</p>
<p id="_">官 報 掲 載 日:平成12年2月1日</p>
````

**Comment by opoudjis** [comment]
And if Japanese numbering is specified for the document (as has been done for the vertical printing thing), the numbers go to Kanji.

Default:

````
     <iso-standard xmlns="http://riboseinc.com/isoxml" type="presentation">
        <bibdata>
          <language current="true">ja</language>
        <date type="created">令和2年10月11日</date>
      <date type="issued">令和2年10月</date>
      <date type="published">令和2年</date>
        </bibdata>
      </iso-standard>
````

Japanese numbering specified:

````
       <iso-standard xmlns="http://riboseinc.com/isoxml" type="presentation">
          <bibdata>
             <language current="true">ja</language>
             <date type="created">令和二年十月十一日</date>
             <date type="issued">令和二年十月</date>
             <date type="published">令和二年</date>
          </bibdata>
       </iso-standard>
````

**Comment by ReesePlews** [comment]
hello @opoudjis thank you for checking this issue. you said:

> And yes, this is also going to change Plateau, since Plateau inherits from JIS.

there is no change for JIS, it is correct as currently defined, and as shown below

JIS uses this type of date format:
![image](https://github.com/user-attachments/assets/f064697c-00ca-403d-bff3-a14611b07112)

i thought because Plateau is a unique flavor it should be possible define that date string differently. is that not possible? i am sorry i am not 100% clear on the details of "inherits from JIS" or why there are changes shown above. perhaps best to discuss more with @ronaldtse.  thank you.

**Comment by opoudjis** [comment]
It is possible, but it will need to be coded explicitly for Plateau. Luckily it's a two-line code update.

**Comment by opoudjis** [comment]
![Screenshot 2024-12-13 at 17 18 47](https://github.com/user-attachments/assets/879ceec7-915a-4c4f-9787-9ac8075f4e7c)

**Comment by ReesePlews** [comment]
hello @opoudjis thank you for making this change, but i wonder why, in the image you provided, the text became centered; however i am not checking the output. the plateau format is shown in the first image in this issue. only the date string required modification. the layout was correct. if i am misunderstanding something, please let me know. if you need clarification, and i will paste in a mockup image of what is required for Plateau.

**Comment by opoudjis** [comment]
That text in the PDF and its formatting is wholly the responsibility of my colleague @Intelligent2013 , so I can't do anything about it: I'm only providing him with the formatted dates to insert into it. If it is not rendering as expected, please raise an issue with him. 

(In fact, Alex, shouldn't I be generating that text as boilerplate?)

**Comment by opoudjis** [comment]
I'll add that this was just a throwaway document with very little metadata, which I only generated to test the date, so it may format properly if more metadata is added into the document.

**Comment by ronaldtse** [comment]
Eventually we should allow the customization of dates just like how we do numbers now. Liquid has also a “date” command that allows reformatting of dates, and we can take heed from that and strftime.

**Comment by ReesePlews** [comment]
hello @opoudjis thank you for the clarifications. i will wait to hear from @Intelligent2013 about the status on revisions. 

i like the idea that @ronaldtse has proposed, and while i dont understand the technical details 100% i think it could be something worth looking into -- in the future.

**Comment by Intelligent2013** [comment]
Plateau XSLT concatenates the publication date from `bibdata/date[@type = 'published']` and static text ` 発行`.

The last page rendering so:
```xml
<fo:block margin-left="4.5mm" margin-top="1mm">
	<xsl:value-of select="/*/bibdata/title[@language = 'ja' and @type = 'title-main']"/>
	<fo:inline padding-left="4mm">
		<xsl:value-of select="/*/bibdata/edition[@language = 'ja']"/>
	</fo:inline>
</fo:block>
<fo:block margin-left="7.7mm">
	<xsl:value-of select="/*/bibdata/date[@type = 'published']"/>
	<xsl:text> 発行</xsl:text>
</fo:block>
<fo:block margin-left="7.7mm">
	<xsl:value-of select="/*/bibdata/contributor[role/@type = 'author']/organization/name"/>
</fo:block>
<fo:block margin-left="9mm">
	<xsl:value-of select="/*/bibdata/contributor[role/@type = 'enabler']/organization/name"/>
</fo:block>
```

![image](https://github.com/user-attachments/assets/4373130b-2c76-48c8-9dc5-9af552483471)

**Comment by ReesePlews** [comment]
thank you for checking this @Intelligent2013. 

the image shown is the current styling, however we want to change the date from:
current:  令和六年9月30日
change to: 令和6年 3月22日

no other part of the text will change, only that "year" part of the date "六" change to "6" (kanji to a number).

thank you.

**Comment by Intelligent2013** [comment]
> (In fact, Alex, shouldn't I be generating that text as boilerplate?)

@opoudjis  currently, the XSLT code is working well I hope. If you will generate the boilerplate, then the markup should contains some indication about the content (title, date, author, enabler), because first paragraph indents with 4.5mm, 2nd and 3rd with 7.7mm, and last with 9mm.

**Comment by opoudjis** [comment]
> > (In fact, Alex, shouldn't I be generating that text as boilerplate?)
> 
> @opoudjis currently, the XSLT code is working well I hope. If you will generate the boilerplate, then the markup should contains some indication about the content (title, date, author, enabler), because first paragraph indents with 4.5mm, 2nd and 3rd with 7.7mm, and last with 9mm.

I see.

Well, I *should* be generating that text for consistency—after all, it will not apear in the HTML output otherwise; but it's not urgent to. I will raise a ticket.

**Comment by opoudjis** [comment]
> Eventually we should allow the customization of dates just like how we do numbers now. Liquid has also a “date” command that allows reformatting of dates, and we can take heed from that and strftime.

strftime alternates between different forms of notation with quite arbitrary use of flags: %y as two-digit year, %Y as four-digit year, %B as name of month, %b as truncated name of month, %m, as zero-padded month digit, %-m as unpadded month digit. Specifying a Roman numeral for month (which is Continental European practice), or Japanese instead of Arabic numerals for date numbers, is going to take a lot more than strftime out of the box. twitter-cldr-rb also seems to have gone in a wrong-headedly inflexible direction with date specification. (I can't even tell if twitter-cldr-rb supports Roman numeral months at all.) 

https://metacpan.org/pod/POSIX::strftime::GNU

I see "alternative numeric symbols" are allowed through the modifiers O and E: %0m is an alternative numeric symbol for a month (which can be a Roman numeral, as confirmed in https://manpages.ubuntu.com/manpages/focal/man3/strftime.3.html ), and %EY is a locale-dependent representation of the year (which might be the regnal year—but which doesn't give us the alternation between numeric and Kanji regnal years).

https://pubs.opengroup.org/onlinepubs/7908799/xsh/strftime.html

Reading that, %Ey is an offest from a base year %EC, and that implies a regnal year (per https://stat.ethz.ch/R-manual/R-devel/library/base/html/strptime.html, E stands for "era", e.g. different religious calendar); but that spec still doesn't give numeric vs Kanji regnal year: %Oy is defined as offset from %C, in other words two-digit year in the century.

strftime is going to need a lot of extending to cope with East Asian dates, and we should try to find out whether anything of the sort has been attempted in East Asia.

I see twitter-cldr is based loosely on the Unicode CLDR values for dates:

https://unicode-org.github.io/icu/userguide/format_parse/datetime/

https://www.unicode.org/reports/tr35/tr35-dates.html#Contents

In that spec, the regnal year is covered as G for the emperor and y for the year; but the CLDR spec does not allow alternation between different numbering systems at all. CLDR seems to be hardcoded to Arabic numerals, including notions of significant digits, and will need to be extended if we want it to alternate between Roman, Arabic, and Chinese numerals.

**Comment by ReesePlews** [comment]
hello @opoudjis and @Intelligent2013 thank you both for this discussion and original revision.

i wanted to add here that before (and with) the Dec 23rd release i was able to confirm that Alex's revision worked. since we have a review and the delivery coming up, and as long as the changes Alex has made here will not cause issues to the future releases of MN through March, i would like to request that nothing be changed or revised on this issue until after April 2025.  

if my request causes and issue, please let me know. thank you.
