### ISSUE TITLE
Wrong metadata warning from JIS: "invalid doctype"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#44]
During compilation at the end we get this:

```
[info]: Building collection file: ~/src/mn/mn-samples-plateau/_site/documents.xml ...
[relaton-jis] WARNING: invalid doctype: `handbook`
[relaton-jis] WARNING: invalid doctype: `handbook`
[info]: Generating html site in ~/src/mn/mn-samples-plateau/_site ...
[relaton-jis] WARNING: invalid doctype: `handbook`
[relaton-jis] WARNING: invalid doctype: `handbook`
Site has been generated at ~/src/mn/mn-samples-plateau/_site
```

This is because the underlying flavor is JIS but this is clearly not a JIS document and it's using the wrong criteria.

**Comment by ronaldtse** [comment]
@andrew2net is this fixed? Thanks.

**Comment by andrew2net** [comment]
@ronaldtse yes, if we use relaton-plateau we won't have invalid doctype messages for these types.

**Comment by andrew2net** [comment]
@ronaldtse @opoudjis can we close this issue?

**Comment by opoudjis** [comment]
Sorry, never noticed this. Yes, I am getting the bibdata from relaton-plateau, and yes, "handbook" is gone: closing.
