### ISSUE TITLE
Implement "commentary" for PLATEAU

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#60]
As in BSI, we have the "commentary" type of admonition. We need to implement it for PLATEAU.

**Comment by opoudjis** [comment]
Wait, if you've presented JIS, then it's not commentary admonitions, but commentary appendixes. if you want the BSI admonitions, please confirm, but https://github.com/metanorma/metanorma-plateau/issues/67 points to commentaries as appendixes.

**Comment by opoudjis** [comment]
@ronaldtse Reminder that the remaining Plateau update issues are all pending responses from you.

**Comment by opoudjis** [comment]
They are the JIS commentaries, so closing.
