### ISSUE TITLE
style issue: PDF renders overlapping text between rows/cols in tables

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-plateau#66]
generate of 20240728 doc01 results in some overlapping text in tables.

**PDF**
![image](https://github.com/user-attachments/assets/45e9f4ef-37fb-46b7-b079-5312fc829e60)

![image](https://github.com/user-attachments/assets/c8402607-87e9-4ffa-bc9a-4d1801d69e96)

**HTML**
![3D_3D_-_2024-07-30_12_48_21](https://github.com/user-attachments/assets/d173124d-659e-4832-8f9b-5b1fc5f1dc89)

i am not generating a word file.

in the case of these tables, the first column could be wider, i am not sure if that is a style issue with the flavor or a document coding issue.

when the columns are narrow, is there a way to split those words (values) in column 1?  i believe MS-Word has a setting that enables non-japanese words to be auto-wrapped, and that wrapping is not the same as "hyphenation" in a western document. 

it may be helpful to investigate this auto-wrapping of non-japanese words.

**Comment by Intelligent2013** [comment]
@ronaldtse each of these tables has the fixed columns widths `[cols="3a,22a"]`.
How to fix:
- option 1: remove widths `[cols="a,a"]`, then 'auto-layout' algorithm will be applied:
![image](https://github.com/user-attachments/assets/48d9923d-3039-4acd-9f2b-351922aeb9b3)

- option 2: set more width for 1st columns in each table like this `[cols="9a,22a"]` if we need the identical columns width across tables.
![image](https://github.com/user-attachments/assets/3c0acf4a-3d71-45fb-9a0d-73afbb43fee4)

**Comment by Intelligent2013** [comment]
> if i am understanding correctly these are "code" issues in the .adoc file and not related to the "flavor" style, is that correct?

@ReesePlews yes. it's the source document encoding issue.
