### ISSUE TITLE
PLATEAU accepted proposal 2: clause and list styling / 箇条及び細分箇条とリストラベルの定義

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#68]
From: https://github.com/metanorma/metanorma-plateau/issues/64

Our proposal is accepted (left):
細別の書式は、JIS 規則の採用を推奨	

PLATEAU note: 
We prefer ISO House style for subdivisions. Use ISO list style, not JIS style.

<img width="714" alt="Screenshot 2024-07-30 at 12 00 13 PM" src="https://github.com/user-attachments/assets/9d476e41-6da6-45c6-a021-87abdf4589b5">

<img width="711" alt="Screenshot 2024-07-30 at 11 59 52 AM" src="https://github.com/user-attachments/assets/3b44811c-e7c6-45ef-a536-9d079c742e93">

So it will be:
* ISO DIR 2 clause numbers
* ISO House Style list numbering and unnumbered em-dashes

**Comment by opoudjis** [comment]
... What about the idiosyncratic numbering of 4th, 5th, 6th level clauses implemented in https://github.com/metanorma/metanorma-plateau/issues/33 ? Is that now being rescinded?

**Comment by ronaldtse** [comment]
@opoudjis yes, they are being rescinded as per the latest proposal accepted by PLATEAU.
