### ISSUE TITLE
PLATEAU accepted proposal 3: Terms and definitions / 用語及び定義箇条の義務付け

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#69]
From: https://github.com/metanorma/metanorma-plateau/issues/64

Our proposal is accepted (left):
JIS 規則の採用を推奨

PLATEAU note: 
Accept. Use JIS terms and definitions style

<img width="713" alt="Screenshot 2024-07-30 at 12 02 04 PM" src="https://github.com/user-attachments/assets/e831fd19-b4ca-4b7f-99e1-7842d5834c12">

**Comment by opoudjis** [comment]
Already implemented, inherited from JIS < ISO.
