### ISSUE TITLE
PLATEAU accepted proposal 6: Notes and Footnotes / 注

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#72]
From: https://github.com/metanorma/metanorma-plateau/issues/64

Our proposal is accepted (left):
規格の本文の注は通常本文中の特定の語句、文及び一部の事項に対する追加情報を提供するために用いる。規格は本文の注がなくても利用できるものでなければならない。→JIS 規則の採用を推奨	

PLATEAU note: 
Use JIS Notes and footnotes.

**Comment by opoudjis** [comment]
Already implemented, inherited from JIS < ISO.
