### ISSUE TITLE
PLATEAU accepted proposal 7: Formula / 式

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#73]
From: https://github.com/metanorma/metanorma-plateau/issues/64

Our proposal is accepted:
外部参照を可能にするため、すべての数式に番号を付ける。→JIS 規則の採用を推奨	

PLATEAU note: 
Use JIS Formula.

**Comment by opoudjis** [comment]
Already implemented: inherited from JIS < ISO.
