### ISSUE TITLE
PLATEAU accepted proposal 8: Figure / 図

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#74]
From: https://github.com/metanorma/metanorma-plateau/issues/64

Our proposal is accepted:
表の中の図に連番をつけ、標題を明記する→JIS 規則の採用を推奨

PLATEAU note: 
We would like to omit the titles of the figures contained in particular tables, if possible. slide 34.

Slide 34:
<img width="719" alt="Screenshot 2024-07-30 at 12 29 31 PM" src="https://github.com/user-attachments/assets/55900ce7-dbb5-460a-baf4-9718bcfe2e1c">

**Comment by opoudjis** [comment]
Naming figures embedded within tables is something that is happening throughout Metanorma, and I find it hard to regard as anything but a bug. There has been pushback at Metanorma regarding assets embedded within other assets as errors (https://github.com/metanorma/mn-samples-itu/issues/159), but I am going to get rid of this nested figure titling at the root, in isodoc.

**Comment by opoudjis** [comment]
Otherwise, implemented, inherited from JIS < ISO.

**Comment by ronaldtse** [comment]
I wonder if this can be a document option or an easy thing per flavor. I'm not convinced that this should be a hard "rule" for all images in tables.
