### ISSUE TITLE
PLATEAU accepted proposal 9: Tables / 表

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#75]
From: https://github.com/metanorma/metanorma-plateau/issues/64

Our proposal is accepted:
注等は、一番下に欄を作って記載する→JIS 規則の採用を推奨

PLATEAU note: 
Use JIS Tables.

**Comment by opoudjis** [comment]
Already implemented, inherited from JIS (which have made rendering modifications on ISO tables, and introduce more content to them.)
