### ISSUE TITLE
PLATEAU accepted proposal 10: Source / 出典

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#76]
From: https://github.com/metanorma/metanorma-plateau/issues/64

Our proposal is accepted:
規格の利用上の利便性などから、引用・参照する規格などの内容を転載する必要がある場合には繰り 返した内容の後に“(出典:○○)”と出典元を正確に記載する。→JIS 規則の採用を推奨

PLATEAU note: 
Adopt JIS source.

**Comment by opoudjis** [comment]
Already implemented, inherited from JIS < ISO, except for sources on Paragraphs and Lists (realised as Proposal 12, https://github.com/metanorma/metanorma-plateau/issues/78 )
