### ISSUE TITLE
PLATEAU accepted proposal 12: Source for paragraphs / 孤立注（注記？）

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#78]
From: https://github.com/metanorma/metanorma-plateau/issues/64

Our proposal is accepted:
規格の理解又は利用を支援するための追加情報を提供するために用いる。規格は注記がなくても利用できるものでなければならない。→JIS 規則の採用を推奨

PLATEAU note: 
We apply JIS style as long as the content is a note. If not, we edit it directly in adoc file.

**Comment by opoudjis** [comment]
If this is not a note, then we have implemented Source on paragraphs already, with rendering as a separate line in brackets, following the paragraph:

````
== Clause

This is a paragraph

[.source]
<<A,clause=3>>

[bibliography]
== Bibliography

* [[[A,PLATEAU Technical Report #00]]]
````

![Screenshot 2024-07-31 at 21 44 18](https://github.com/user-attachments/assets/4e38c435-7645-4513-ac4e-e41849e5037f)
