### ISSUE TITLE
PLATEAU accepted proposal 14: Recommendations / 推奨

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#80]
From: https://github.com/metanorma/metanorma-plateau/issues/64

Our proposal is accepted:
OGC ModSpec 要件モデルを採用する。	

PLATEAU note: 
Use OGC ModSpec for recommendations.

See https://github.com/metanorma/metanorma-plateau/issues/79 for original proposal.

**Comment by opoudjis** [comment]
Implemented in https://github.com/metanorma/metanorma-plateau/issues/79
