### ISSUE TITLE
PLATEAU accepted proposal 15: Commentary / 解説

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#81]
From: https://github.com/metanorma/metanorma-plateau/issues/64

Our proposal is accepted:
1，注記として扱う2，注記でない場合は、特別な種類の注記として扱う。

PLATEAU note: 
Accept case 2. Implement as commentary.

**Comment by opoudjis** [comment]
Commentary will be put at the end of the document: inherited from JIS. At this time, will render like JIS commentaries, with the title of the document at the start.
