### ISSUE TITLE
PLATEAU accepted proposal 17: Bibliography / 引用

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#83]
From: https://github.com/metanorma/metanorma-plateau/issues/64

Our proposal is accepted:
参照タグの定義づけのルールがいる

PLATEAU note: 
We don't need reference tag, but need number for each referenced document.

[20240723 plateau proposal confirmation - proposal 17.pdf](https://github.com/user-attachments/files/16422271/20240723.plateau.proposal.confirmation.-.proposal.17.pdf)

**Comment by opoudjis** [comment]
Explanation needed: does this mean that in the Bibliography, numbers must appear on the left hand side for all references, instead of reference tags for standards? so:

> [1] Plateau Handbook #00.
> [2] ISO 939
> [3] Smith, John. 1939. Book Title.

**Comment by ronaldtse** [comment]
<img width="687" alt="Screenshot 2024-08-14 at 1 21 53 PM" src="https://github.com/user-attachments/assets/275c35f0-05fe-46a6-a40d-3a5e9fb62d2c">

Translation:

- In this bibliography list, what is the reference tag used for the citation? Is it [1] or "Standard Product Specification for 3D City Models Version 1.0"?
- Citation rules are required; it is recommended that PLATEAU documents adopt the special marking rules of JIS.
- For example, is it cited in "PLATEAU Handbook #01 v1.0" as well as "OGC 20-043r2"?
- Should the PLATEAU Handbook be listed first with other standards? In which order are government specifications listed?


We shall adopt JIS style:

* Normative references are never numbered. JIS Z 8301 Clause 15.
* Bibliography items may or may not be numbered (21.4, "The individual references listed may or may not be numbered. The list of references may be grouped under a heading. These headings must not be numbered.")

JIS Z 8301 Annex J template (numbered):
<img width="570" alt="Screenshot 2024-08-14 at 1 38 05 PM" src="https://github.com/user-attachments/assets/8710175c-eb0c-4338-a144-046513914cfd">

JIS Z 8301 itself (unnumbered):
<img width="573" alt="Screenshot 2024-08-14 at 1 38 33 PM" src="https://github.com/user-attachments/assets/ac52a7ac-c499-4c7e-b851-b8ba492ae8f6">

I think it's best to choose always numbered for PLATEAU.

For Normative references, the JIS order is:
> 15.5.2.4 Order of entry
> Normally, the order of cited standards is JIS, ISO standards (including ISO/IEC standards), IEC standards, and other normative documents, in that order.
> The order of the cited standards is usually JIS, ISO standards (including ISO/IEC standards), IEC standards, and other normative documents, in that order. 
> However, when the corresponding International Standard is JIS of an IEC standard, the IEC standard shall be listed before the ISO standard. 
> Among similar standards or normative documents, the order is as follows: standard number or document number, document symbol, and document name (usually in alphabetical order).

The bibliography is unordered but we could enforce the Normative reference ordering.

**Comment by opoudjis** [comment]
Obligatory numbering of all Bibliography references, whether they are standards or not, is already in place. 

By default in Metanorma (following ISO), only bibliography is ordered, and normative references are not. BSI and ITU sort both. I will sort both for JIS as well.

**Comment by opoudjis** [comment]
The sort order I have currently implemented is MLIT < Other standards < Other documents.

You are now telling me to abandon that and inherit JIS ordering. Moreover, this is the first that I've seen the JIS ordering.

**Comment by opoudjis** [comment]
> The order of the cited standards is usually JIS, ISO standards (including ISO/IEC standards), IEC standards, and other normative documents, in that order.
> However, when the corresponding International Standard is JIS of an IEC standard, the IEC standard shall be listed before the ISO standard.

This is not intelligible. I am going to assume it means JIS > JIS/IEC, JIS/ISO/IEC > JIS/ISO > ISO, ISO/IEC > IEC > Other

which is ridiculously self-indulgent.

**Comment by opoudjis** [comment]
Otherwise, the sort order inherits from ISO in its use of number, designation, name.
