### ISSUE TITLE
Bibliography order: PLATEAU first, then standards, then randoms

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#84]
We should list these items in this order:
1. PLATEAU published items
2. Standards
3. Random stuff

<img width="1126" alt="image" src="https://github.com/user-attachments/assets/ea9c858f-df05-4278-8f9d-9d5307e16e86">

**Comment by opoudjis** [comment]
Blocked by: 

* https://github.com/relaton/relaton-plateau/issues/9
* https://github.com/relaton/relaton-plateau/issues/10
