### ISSUE TITLE
Remove Word as output format

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-plateau#88]

**Comment by ReesePlews** [comment]
hi @opoudjis at your convenience, can you clarify what this means? does it mean that MS-Word documents cannot be generated, etc by this flavor, or something different? just trying to figure out based on the title. no hurry with a reply. thanks,

**Comment by opoudjis** [comment]
Yes. I'd confirmed with Ronald that Word output is not required for Plateau, so I've just removed the ability of this gem to generate Word output for Plateau.

**Comment by ReesePlews** [comment]
hello @opoudjis, thank you for the update. 

is removing ms-word ability from the "gem" is a better solution than removing "doc" from the mn-output-extensions?  i thought the output formats were not dependent on the flavor, only output from the xml base.

so if i add "doc" to `:mn-output-extensions: html,pdf,doc` what will happen during generate?

**Comment by opoudjis** [comment]
If I remove the format from the gem, then there is zero (0) code pertaining to it, and therefore zero additional code for me to maintain. (And there is a LOT of idiosyncrasy from the JIS gem's Word output, which I would have to undo if we did maintain Word output.) If you specify doc in mn-output-extensions, Metanorma will complain that you are trying to use a format that is not supported.

So this is not just about what you specify in the document, this is about reducing maintenance burden (supported formats still need to be tested and updated.)
